### PR TITLE
Removes memory_resource.

### PR DESCRIPTION
**Pull request by mzimbres**

### CODE REVIEW

**Comment by mrichmon** [comment]
What is the next planned release that will include this fix?

**Comment by mzimbres** [comment]
Most users seem to be using the develop branch so I did not bother merging in master and creating a new release. I will prepare a new pre-boost release this weekend.

**Comment by mzimbres** [comment]
Just made a release tarball v1.4.2. Docs are not updated yet.

**Comment by mrichmon** [comment]
Thank you.
The companies I've worked with require release checkpoints for open source projects so this release helps.

**Comment by mrichmon** [comment]
Note that `CMakeLists.txt` still has "VERSION 1.4.1" in this 1.4.2 tarball.

**Pull request merged**
